language: ruby
sudo: false
rvm:
  - 2.1
script:
  - bundle exec planet generate
  - bundle exec jekyll build --trace --config _config.yml
  - bundle exec htmlproof ./_posts --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

